main:
	gcc game.c exit.c exit2.c  boundingbox.c save.c main.c quiz.c menu.c menu2.c menu3.c playm.c playm2.c play.c play2.c play3.c  player.c player2.c settings2.c navg.c enemi.c collisionc.c vie.c credits.c objet.c time.c  -lm -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer  -o prog
