main:
	gcc game.c exit.c   boundingbox.c main.c quiz.c menu.c menu2.c 
menu3.c play.c play2.c play3.c  player.c settings2.c clochard.c vie.c credits.c objet.c time.c -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -o prog
